name: TnP Job Alert Bot

on:
  workflow_dispatch:  # Only run when manually triggered from GitHub UI

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Create required files if they don't exist
        run: |
          echo "[]" > seenJobs.json
          echo "[]" > users.json
        working-directory: backend

      - name: Debug environment variables
        run: |
          echo "Checking if secrets are available..."
          echo "GMAIL=$GMAIL"
          echo "GMAIL_PASS is set: ${GMAIL_PASS:+yes}"
          echo "PASSWORD is set: ${PASSWORD:+yes}"
          echo "SECRET_KEY is set: ${SECRET_KEY:+yes}"
        working-directory: backend
        env:
          GMAIL: ${{ secrets.GMAIL }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }} 